server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://demo-api:9099/api/;
    proxy_set_header Host $host;
    proxy_read_timeout 120s;
  }
}
